---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r results='hide'}
packages = c('readr','sp', 'sf', 'rgdal', 'spNetwork', 'tmap', 'FNN', 'spatstat', "raster")
  for (p in packages)
  {
    if(!require(p, character.only = T)){
    install.packages(p)
  }
  library(p,character.only = T)
}
```


```{r}
PDD_Buildings <- read_csv("data/Aspatial/PDD_Buildings.csv")

PDD_Buildings <- st_as_sf(PDD_Buildings, coords = c("LONGITUDE", "LATITUDE"), crs = 4326) %>%
  st_transform(crs = 3414)
```

```{r}
MPSZ <- st_read(dsn = "data", 
              layer = "MP14_SUBZONE_WEB_PL")

PG <- MPSZ[MPSZ$`PLN_AREA_N` == 'PUNGGOL', ]

PG <- as_Spatial(PG)
```

```{r}
PDD <- st_read(dsn = "data", 
                layer = "PDD_Boundary")

PDD <- st_zm(PDD, drop = TRUE, what = "ZM")

Punggol_Digital_District_Boundary <- as_Spatial(PDD)
```
```{r}
JLD <- st_read(dsn = "data/JLD Boundary", 
               layer = "JLD Boundary")

JLD <- st_zm(JLD, drop = TRUE, what = "ZM")

Jurong_Lake_District_Boundary <- as_Spatial(JLD)
```


```{r}
JID <- st_read(dsn = "data/JID Boundary", 
               layer = "JID")

JID <- st_zm(JID, drop = TRUE, what = "ZM")

Jurong_Innovation_District_Boundary <- as_Spatial(JID)
```

